name: "CI/CD for Dockerized Django App"

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils python3-dev build-essential
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Run tests"
        run: |
          python manage.py test

      - name: "Docker Login"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Build Docker image and Push to Docker Hub"
        run: |
          docker build -t ${{ secrets.DOCKERHUB_LOGIN }}/django_app:latest .
          docker push ${{ secrets.DOCKERHUB_LOGIN }}/django_app:latest

      - name: "Deploy to remote server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # Exit immediately if a command exits with a non-zero status.
            docker stop django_app || true
            docker rm django_app || true
            docker run -d --name django_app -p 8000:8000 ${{ secrets.DOCKERHUB_LOGIN }}/django_app:latest
